### ISSUE TITLE
Implement more of the dunder-ndarray interface.

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/unumpy#29]
Implement more of the `ndarray` interface.

# Memory Layout

* [x] [`ndarray.shape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)/`np.shape`
* [x]  [`ndarray.ndim`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.ndim.html#numpy.ndarray.ndim)/`np.ndim`
* [x]  [`ndarray.size`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.size.html#numpy.ndarray.size)/`np.size`
* [x]  [`ndarray.nbytes`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.nbytes.html#numpy.ndarray.nbytes)
* [x] [`ndarray.itemsize`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.itemsize.html#numpy.ndarray.itemsize)

# Transposing

* [x] [`transpose`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html#numpy.transpose)
* [x] [`ndarray.T`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html#numpy.ndarray.T)
* [x] [`swapaxes`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.swapaxes.html#numpy.swapaxes)
* [x] [`rollaxis`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html#numpy.rollaxis)
* [x] [`moveaxis`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.rollaxis.html#numpy.rollaxis)

# Reshaping
* [x] [`reshape`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html#numpy.reshape)
* [x] [`ravel`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ravel.html#numpy.ravel)
* [x] [`ndarray.flatten`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten)

# GetItem and Friends
* [x] [`ndarray.__getitem__`](https://docs.scipy.org/doc/numpy/user/basics.indexing.html)
* [x] [`broadcast_to`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast_to.html#numpy.broadcast_to)/`ndarray.broadcast_to`
* [x] [`broadcast_arrays`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.broadcast_arrays.html#numpy.broadcast_arrays)

# Joining Arrays
* [x] [`concatenate`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.concatenate.html#numpy.concatenate)
* [x] [`stack`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.stack.html#numpy.stack)
* [x] [`column_stack`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.column_stack.html#numpy.column_stack)
* [x] [`hstack`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.hstack.html#numpy.hstack)
* [x] [`vstack`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.vstack.html#numpy.vstack)
* [x] [`block`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.block.html#numpy.block)

**Comment by prasunanand** [comment]
@hameerabbasi , Do I need to add tests for `ndarray.methods` as well ?

**Comment by hameerabbasi** [comment]
Yes.

**Comment by prasunanand** [comment]
I have a doubt here:
I have added test for np.ndim/ndarray.ndim as 
https://github.com/Quansight-Labs/unumpy/pull/30/files#diff-801cbeb7bd729e76ac2c91759b13745dR124

Is this enough ?

**Comment by hameerabbasi** [comment]
Yes, it's good enough.

**Comment by prasunanand** [comment]
Cool. Thanks :)

**Comment by hameerabbasi** [comment]
Closing this since all these are implemented.
