### ISSUE TITLE
bug in arange when using the Dask backend

### ISSUE THREAD

**Issue by grlee77** [Quansight-Labs/unumpy#37]
If `arange` is called without all three positional arguments (`start`, `stop`, `step`) it seems to fail for the Dask backend. It checked that it works as expected for both NumPy and CuPy.

This reason is due to the default implementation in `dask_backend.py`:
https://github.com/Quansight-Labs/unumpy/blob/b54321be35f7ac6df28cc30b8b9c85379883381e/unumpy/dask_backend.py#L83-L85

Here all three arguments will be in *args even if some are None. However, inside of `dask.array.arange`, `len(args)` is used to determine behavior. Here len(args) is **always** 3, so if any of them are None, there will be a bug:
https://github.com/dask/dask/blob/ec16e5ff53c4ff660267061323727ddfbb05f588/dask/array/creation.py#L297-L306

**To reproduce**

```Python
import uarray as ua
import unumpy as np
import unumpy.dask_backend as DaskBackend

with ua.set_backend(DaskBackend):
    ret = np.arange(9)
```

A solution seems to be just removing the default `arange` definition from `dask_backend.py`. Was that there for an older version of Dask where `arange` had not yet been implemented?

**Comment by hameerabbasi** [comment]
> A solution seems to be just removing the default `arange` definition from `dask_backend.py`. Was that there for an older version of Dask where `arange` had not yet been implemented?

I believe not.
