### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by joaosferreira** [Quansight-Labs/unumpy#52]
It seems to be missing the statement `return func` at the end of the above function definition:
https://github.com/Quansight-Labs/unumpy/blob/30c4afde16fbbb231cbc1e20d28cf5f0a8527285/unumpy/_multimethods.py#L78-L83

Can someone verify this?

**Comment by hameerabbasi** [comment]
Yes, that's an oversight. Please feel free to correct it.

**Comment by hameerabbasi** [comment]
Fixed by #53.
