### ISSUE TITLE
Add dispatching over dtypes.

### ISSUE THREAD

**Issue by hameerabbasi** [Quansight-Labs/unumpy#7]
Allow dispatching over dtypes in addition to ufuncs and arrays.
- [x] ufunc

* Array Creation Routines

- [x] eye
- [x] ones
- [x] zeros
- [x] full

* From existing data
- [x] asarray

**Comment by hameerabbasi** [comment]
Deferring this as it doesn't seem to be that big of a priority.

**Comment by prasunanand** [comment]
Ufuncs: https://github.com/Quansight-Labs/unumpy/pull/26

**Comment by prasunanand** [comment]
Fixed by:
* https://github.com/Quansight-Labs/unumpy/pull/26
* https://github.com/Quansight-Labs/unumpy/pull/27
* https://github.com/Quansight-Labs/unumpy/pull/28
