### ISSUE TITLE
Error propagation in determinant

### ISSUE THREAD

**Issue by SJ001** [Quansight-Labs/unumpy#75]
Hello! I would like to do error propagation when calculating the determinant of a matrix (whose elements have errors). Is there a way to do that? I see there is an unumpy.ulinalg package, but it doesn't seem to have a determinant option. Thank you

**Comment by hameerabbasi** [comment]
cc @joaosferreira 

Could you perhaps provide a code example of what you would do in regular NumPy?

**Comment by SJ001** [comment]
Thank you for the fast reply! Here is an example:

```
import numpy as np
from numpy import linalg
M = np.array([[1,2,3],[1,4,1],[5,4,5]])
np.linalg.det(M)
```
In principle one can define the determinant function and it would work with error propagation, too, like this:

```
def determinant(M):
    dim = len(M)
    if dim==2:
        return M[0][0]*M[1][1]-M[0][1]*M[1][0]
    else:
        det = 0
        for i in range(dim):
            N = np.delete(M,i,1)
            N = np.delete(N,0,0)
            det = det + (-1)**i*M[0][i]*determinant(N)
        return det
```

But I was wondering if that is built-in already.

**Comment by hameerabbasi** [comment]
It depends on the back-end you are using. In practice I think it should be implemented on most back-ends.

**Comment by SJ001** [comment]
I am not sure what you mean. This doesn't work:

```
M = unumpy.uarray([[1,2,3],[1,4,1],[5,4,5]],[[0.1,0.1,0.1],[0.1,0.1,0.1],[0.1,0.1,0.1]])
unumpy.ulinalg.det(M)
```

**Comment by hameerabbasi** [comment]
Oh, you need to use a back-end. You aren't doing that currently, see this page:

https://uarray.org/en/latest/enduser_docs.html

The available backends are found here:

https://github.com/Quansight-Labs/unumpy/tree/master/unumpy

They are the `*_backend` files.

**Comment by hameerabbasi** [comment]
Please re-open if you have any other questions or issues.
